<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.10.18">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Ronnie Keene">

<title>Predicting Wage Complaint Resolution Times – Ronnie Keene</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: 1.5em;}
div.column{flex: auto;}
@media screen {
div.columns{gap: min(4vw, 1.5em);}
div.column{overflow-x: auto;}
}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.min.js" integrity="sha384-ZvpUoO/+PpLXR1lu4jmpXWu80pZlYUAfxl5NsBMWOEPSjUn/6Z/hRTt8+pR6L4N2" crossorigin="anonymous"></script><script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<script src="../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-64a204ab8560d761af7679ceaba22944.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap-172ba59bd5e0b52282274ba0c0cc16fc.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<script src="https://cdn.jsdelivr.net/npm/requirejs@2.3.6/require.min.js" integrity="sha384-c9c+LnTbwQ3aujuU7ULEPVvgLs+Fn6fJUvIGTsuu1ZcCf11fiEubah0ttpca4ntM sha384-6V1/AdqZRWk1KAlWbKBlGhN7VG4iE/yAZcO6NZPMF8od0vukrvr0tg4qY6NSrItx" crossorigin="anonymous"></script>

<script type="application/javascript">define('jquery', [],function() {return window.jQuery;})</script>


</head>

<body class="nav-fixed quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../index.html">
    <span class="navbar-title">Ronnie Keene</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../index.html"> 
<span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../about.html"> 
<span class="menu-text">About</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link active" href="../projects/wage-complaint-resolution.html" aria-current="page"> 
<span class="menu-text">Projects</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#overview" id="toc-overview" class="nav-link active" data-scroll-target="#overview">Overview</a>
  <ul class="collapse">
  <li><a href="#tools" id="toc-tools" class="nav-link" data-scroll-target="#tools">Tools</a></li>
  </ul></li>
  <li><a href="#data-and-feature-engineering" id="toc-data-and-feature-engineering" class="nav-link" data-scroll-target="#data-and-feature-engineering">Data and Feature Engineering</a></li>
  <li><a href="#first-approach-ordinary-linear-regression" id="toc-first-approach-ordinary-linear-regression" class="nav-link" data-scroll-target="#first-approach-ordinary-linear-regression">First Approach: Ordinary Linear Regression</a>
  <ul class="collapse">
  <li><a href="#modeling-only-completed-complaints" id="toc-modeling-only-completed-complaints" class="nav-link" data-scroll-target="#modeling-only-completed-complaints">Modeling Only Completed Complaints</a></li>
  <li><a href="#full-regression-baseline" id="toc-full-regression-baseline" class="nav-link" data-scroll-target="#full-regression-baseline">Full Regression Baseline</a></li>
  <li><a href="#cross-validation" id="toc-cross-validation" class="nav-link" data-scroll-target="#cross-validation">Cross-Validation</a></li>
  <li><a href="#trying-simpler-specifications" id="toc-trying-simpler-specifications" class="nav-link" data-scroll-target="#trying-simpler-specifications">Trying Simpler Specifications</a></li>
  </ul></li>
  <li><a href="#why-change-the-modeling-framework" id="toc-why-change-the-modeling-framework" class="nav-link" data-scroll-target="#why-change-the-modeling-framework">Why Change the Modeling Framework?</a></li>
  <li><a href="#survival-analysis" id="toc-survival-analysis" class="nav-link" data-scroll-target="#survival-analysis">Survival Analysis</a>
  <ul class="collapse">
  <li><a href="#constructing-the-time-to-event-data" id="toc-constructing-the-time-to-event-data" class="nav-link" data-scroll-target="#constructing-the-time-to-event-data">Constructing the Time-to-Event Data</a></li>
  <li><a href="#kaplanmeier-estimate" id="toc-kaplanmeier-estimate" class="nav-link" data-scroll-target="#kaplanmeier-estimate">Kaplan–Meier Estimate</a></li>
  </ul></li>
  <li><a href="#parametric-accelerate-failure-time-models" id="toc-parametric-accelerate-failure-time-models" class="nav-link" data-scroll-target="#parametric-accelerate-failure-time-models">Parametric Accelerate Failure-Time Models</a>
  <ul class="collapse">
  <li><a href="#holdout-performance" id="toc-holdout-performance" class="nav-link" data-scroll-target="#holdout-performance">Holdout Performance</a></li>
  <li><a href="#five-fold-cross-validation" id="toc-five-fold-cross-validation" class="nav-link" data-scroll-target="#five-fold-cross-validation">Five-Fold Cross-Validation</a></li>
  </ul></li>
  <li><a href="#exploring-differences-in-resolution-curves" id="toc-exploring-differences-in-resolution-curves" class="nav-link" data-scroll-target="#exploring-differences-in-resolution-curves">Exploring Differences in Resolution Curves</a>
  <ul class="collapse">
  <li><a href="#example-kaplanmeier-comparison" id="toc-example-kaplanmeier-comparison" class="nav-link" data-scroll-target="#example-kaplanmeier-comparison">Example Kaplan–Meier Comparison</a></li>
  </ul></li>
  <li><a href="#an-exploratory-reduced-model" id="toc-an-exploratory-reduced-model" class="nav-link" data-scroll-target="#an-exploratory-reduced-model">An Exploratory Reduced Model</a></li>
  <li><a href="#what-i-learned" id="toc-what-i-learned" class="nav-link" data-scroll-target="#what-i-learned">What I Learned</a></li>
  <li><a href="#limitations-and-next-steps" id="toc-limitations-and-next-steps" class="nav-link" data-scroll-target="#limitations-and-next-steps">Limitations and Next Steps</a></li>
  <li><a href="#bottom-line" id="toc-bottom-line" class="nav-link" data-scroll-target="#bottom-line">Bottom Line</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Predicting Wage Complaint Resolution Times</h1>
<p class="subtitle lead">From Linear Regression to Survival Analysis</p>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Ronnie Keene </p>
          </div>
  </div>
    
  
    
  </div>
  


</header>


<section id="overview" class="level2">
<h2 class="anchored" data-anchor-id="overview">Overview</h2>
<p>How much can the information available in a 311 wage complaint tell us about how long that complaint will remain open?</p>
<p>I explored this question using <strong>374 wage complaints</strong> and a set of features describing the issues raised in each complaint, the quality and content of its written description, and characteristics such as whether multiple workers were involved. The complaints were taken from a backend version of the City of Chicago’s 311 system. This backend access featured complaints encrypted by the Office of Labor Standards, but I was still able to read each complaint’s “description” field. These descriptions formed the basis for each complaint’s features. The date range within which complaints were opened spanned from July 17, 2025 to July 17, 2026.</p>
<p>I began with ordinary linear regression on completed complaints, then moved to survival analysis so that complaints still open at the end of the observation period could remain in the analysis as right-censored observations.</p>
<p>The modeling results are intentionally modest. The linear models did not generalize well, and the survival models achieved only moderate ranking performance. The more important result was methodological: <strong>time-to-resolution is better framed as a censored time-to-event problem than as an ordinary regression problem that discards every complaint still open.</strong></p>
<section id="tools" class="level3">
<h3 class="anchored" data-anchor-id="tools">Tools</h3>
<p>Python, pandas, NumPy, scikit-learn, matplotlib, and <code>lifelines</code>.</p>
</section>
</section>
<section id="data-and-feature-engineering" class="level2">
<h2 class="anchored" data-anchor-id="data-and-feature-engineering">Data and Feature Engineering</h2>
<p>The source data contain timestamps for when each complaint was opened and, when applicable, closed. The remaining variables are primarily binary indicators describing the complaint.</p>
<p>The issue indicators include categories such as overtime, minimum wage, final paycheck, deductions or benefits, retaliation, tips, payroll records, and leave or vacation pay. Additional engineered variables describe features of the complaint narrative, including whether evidence was mentioned, whether multiple workers were involved, and an ordinal description-quality score.</p>
<div id="load-data" class="cell" data-execution_count="2">
<details class="code-fold">
<summary>Show code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>DATA_PATH <span class="op">=</span> <span class="st">'data/complaints_dummy_variables.csv'</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a>complaints <span class="op">=</span> pd.read_csv(DATA_PATH)</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a>complaints[<span class="st">"closed_status"</span>] <span class="op">=</span> (</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a>    complaints[<span class="st">"Date/Time Closed"</span>].notna().astype(<span class="bu">int</span>)</span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a>complaints[<span class="st">"Date/Time Opened"</span>] <span class="op">=</span> pd.to_datetime(</span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a>    complaints[<span class="st">"Date/Time Opened"</span>],</span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a>    <span class="bu">format</span><span class="op">=</span><span class="st">"%Y-%m-</span><span class="sc">%d</span><span class="st"> %H:%M:%S"</span></span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb1-13"><a href="#cb1-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-14"><a href="#cb1-14" aria-hidden="true" tabindex="-1"></a>complaints[<span class="st">"Date/Time Closed"</span>] <span class="op">=</span> pd.to_datetime(</span>
<span id="cb1-15"><a href="#cb1-15" aria-hidden="true" tabindex="-1"></a>    complaints[<span class="st">"Date/Time Closed"</span>],</span>
<span id="cb1-16"><a href="#cb1-16" aria-hidden="true" tabindex="-1"></a>    <span class="bu">format</span><span class="op">=</span><span class="st">"%Y-%m-</span><span class="sc">%d</span><span class="st"> %H:%M:%S"</span></span>
<span id="cb1-17"><a href="#cb1-17" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb1-18"><a href="#cb1-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-19"><a href="#cb1-19" aria-hidden="true" tabindex="-1"></a>complaints[<span class="st">"completion_duration"</span>] <span class="op">=</span> (</span>
<span id="cb1-20"><a href="#cb1-20" aria-hidden="true" tabindex="-1"></a>    complaints[<span class="st">"Date/Time Closed"</span>] <span class="op">-</span> complaints[<span class="st">"Date/Time Opened"</span>]</span>
<span id="cb1-21"><a href="#cb1-21" aria-hidden="true" tabindex="-1"></a>).dt.total_seconds() <span class="op">/</span> <span class="dv">86400</span></span>
<span id="cb1-22"><a href="#cb1-22" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-23"><a href="#cb1-23" aria-hidden="true" tabindex="-1"></a>complaints[<span class="st">"description_blank"</span>] <span class="op">=</span> (</span>
<span id="cb1-24"><a href="#cb1-24" aria-hidden="true" tabindex="-1"></a>    complaints[<span class="st">"description_quality"</span>].isna().astype(<span class="bu">int</span>)</span>
<span id="cb1-25"><a href="#cb1-25" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb1-26"><a href="#cb1-26" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-27"><a href="#cb1-27" aria-hidden="true" tabindex="-1"></a>complaints[<span class="st">"description_quality"</span>] <span class="op">=</span> (</span>
<span id="cb1-28"><a href="#cb1-28" aria-hidden="true" tabindex="-1"></a>    complaints[<span class="st">"description_quality"</span>] <span class="op">+</span> <span class="dv">1</span></span>
<span id="cb1-29"><a href="#cb1-29" aria-hidden="true" tabindex="-1"></a>).fillna(<span class="dv">0</span>)</span>
<span id="cb1-30"><a href="#cb1-30" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-31"><a href="#cb1-31" aria-hidden="true" tabindex="-1"></a>complaints <span class="op">=</span> pd.get_dummies(</span>
<span id="cb1-32"><a href="#cb1-32" aria-hidden="true" tabindex="-1"></a>    complaints,</span>
<span id="cb1-33"><a href="#cb1-33" aria-hidden="true" tabindex="-1"></a>    columns<span class="op">=</span>[<span class="st">"description_quality"</span>],</span>
<span id="cb1-34"><a href="#cb1-34" aria-hidden="true" tabindex="-1"></a>    dtype<span class="op">=</span><span class="bu">int</span></span>
<span id="cb1-35"><a href="#cb1-35" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb1-36"><a href="#cb1-36" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-37"><a href="#cb1-37" aria-hidden="true" tabindex="-1"></a>complaints <span class="op">=</span> complaints.rename(</span>
<span id="cb1-38"><a href="#cb1-38" aria-hidden="true" tabindex="-1"></a>    columns<span class="op">=</span>{<span class="st">"Unclear"</span>: <span class="st">"ambiguous_primary"</span>}</span>
<span id="cb1-39"><a href="#cb1-39" aria-hidden="true" tabindex="-1"></a>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
<div id="cell-sample-summary" class="cell" data-execution_count="3">
<div id="sample-summary" class="cell-output cell-output-display" data-execution_count="3">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">Status</th>
<th data-quarto-table-cell-role="th">Count</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<th data-quarto-table-cell-role="th">0</th>
<td>All complaints</td>
<td>374</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">1</th>
<td>Closed</td>
<td>252</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">2</th>
<td>Still open</td>
<td>122</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<p>The dataset contains <strong>374 complaints: 252 closed complaints and 122 complaints that were still open</strong> at the censoring point used in the analysis. That distinction becomes important later.</p>
</section>
<section id="first-approach-ordinary-linear-regression" class="level2">
<h2 class="anchored" data-anchor-id="first-approach-ordinary-linear-regression">First Approach: Ordinary Linear Regression</h2>
<section id="modeling-only-completed-complaints" class="level3">
<h3 class="anchored" data-anchor-id="modeling-only-completed-complaints">Modeling Only Completed Complaints</h3>
<p>My first approach treated completion time as a standard continuous response variable. Because an unresolved complaint does not yet have a final completion time, this required removing every complaint that was still open.</p>
<div id="cell-completed-cases" class="cell" data-execution_count="4">
<div id="completed-cases" class="cell-output cell-output-display" data-execution_count="4">
<pre><code>count    252.000000
mean      37.379823
std       38.427271
min        0.001389
25%       10.673958
50%       33.018750
75%       42.171528
max      260.274306
Name: completion_duration, dtype: float64</code></pre>
</div>
</div>
<p>Among the completed complaints, the mean observed completion time in the notebook was approximately <strong>37.4 days</strong>. The distribution was also right-skewed.</p>
<div id="cell-completion-histogram" class="cell" data-execution_count="5">
<div class="cell-output cell-output-display">
<div id="completion-histogram" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="wage-complaint-resolution_files/figure-html/completion-histogram-output-1.png" width="659" height="429" class="figure-img"></p>
<figcaption>Distribution of resolution times among completed complaints.</figcaption>
</figure>
</div>
</div>
</div>
</section>
<section id="full-regression-baseline" class="level3">
<h3 class="anchored" data-anchor-id="full-regression-baseline">Full Regression Baseline</h3>
<p>For the initial multivariable model, I used issue indicators, complaint-characteristic indicators, and dummy variables for description quality. I excluded <code>issue_count</code> from the full model after diagnosing multicollinearity with the individual issue indicators. The all-zero description-quality category serves as the reference category.</p>
<div id="cell-regression-test-results" class="cell" data-execution_count="7">
<div id="regression-test-results" class="cell-output cell-output-display" data-execution_count="7">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">Metric</th>
<th data-quarto-table-cell-role="th">Test result</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<th data-quarto-table-cell-role="th">0</th>
<td>R²</td>
<td>-0.216150</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">1</th>
<td>MAE (days)</td>
<td>30.797938</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">2</th>
<td>RMSE (days)</td>
<td>45.811908</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<p>In the original notebook, the holdout model produced:</p>
<ul>
<li><strong>R² = -0.216</strong></li>
<li><strong>MAE = 30.8 days</strong></li>
<li><strong>RMSE = 45.8 days</strong></li>
</ul>
<p>A negative test R² means the fitted model generalized worse than simply predicting the test set using a constant mean benchmark.</p>
</section>
<section id="cross-validation" class="level3">
<h3 class="anchored" data-anchor-id="cross-validation">Cross-Validation</h3>
<p>I also evaluated the model with five-fold cross-validation on the training set.</p>
<div id="cell-regression-cv" class="cell" data-execution_count="8">
<div id="regression-cv" class="cell-output cell-output-display" data-execution_count="8">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">Metric</th>
<th data-quarto-table-cell-role="th">Value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<th data-quarto-table-cell-role="th">0</th>
<td>Mean CV R²</td>
<td>-0.176149</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">1</th>
<td>SD of CV R²</td>
<td>0.283964</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">2</th>
<td>Mean CV MAE (days)</td>
<td>26.209585</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<p>The original five folds produced a <strong>mean CV R² of -0.176</strong> and a <strong>mean CV MAE of 26.2 days</strong>. Performance varied substantially across folds, reinforcing the conclusion that the available intake features did not support a reliable linear prediction of final completion time.</p>
</section>
<section id="trying-simpler-specifications" class="level3">
<h3 class="anchored" data-anchor-id="trying-simpler-specifications">Trying Simpler Specifications</h3>
<p>I tested whether the poor performance was mainly a consequence of the large predictor set or the skewed response. The notebook compared models using only issue count, only description quality, a square-root transformation of completion time, and a smaller set of issue indicators.</p>
<div id="cell-regression-alternatives" class="cell" data-execution_count="9">
<div id="regression-alternatives" class="cell-output cell-output-display" data-execution_count="9">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">Specification</th>
<th data-quarto-table-cell-role="th">Mean 5-fold CV R²</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<th data-quarto-table-cell-role="th">0</th>
<td>Full intake-feature model</td>
<td>-0.1761</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">1</th>
<td>Issue count only</td>
<td>-0.0431</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">2</th>
<td>Description quality only</td>
<td>-0.0593</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">3</th>
<td>Full model, sqrt(response)</td>
<td>-0.1578</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">4</th>
<td>Issue count only, sqrt(response)</td>
<td>-0.0101</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">5</th>
<td>Issue indicators only, sqrt(response)</td>
<td>-0.0567</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<p>None of these specifications produced positive mean cross-validated R². Transforming the response improved its shape but did <strong>not</strong> solve the underlying prediction problem.</p>
</section>
</section>
<section id="why-change-the-modeling-framework" class="level2">
<h2 class="anchored" data-anchor-id="why-change-the-modeling-framework">Why Change the Modeling Framework?</h2>
<p>The linear-regression experiment exposed a more fundamental problem.</p>
<p>To use ordinary regression, I had removed <strong>122 unresolved complaints — nearly one-third of the dataset</strong> — solely because their final completion times were not yet known. Those complaints are not missing in the usual sense. Each one tells us something important: the complaint had remained open for <em>at least</em> a known amount of time.</p>
<p>That is a classic <strong>right-censoring</strong> problem.</p>
<p>Survival analysis allows those observations to contribute information without pretending that their eventual closure times are already known.</p>
</section>
<section id="survival-analysis" class="level2">
<h2 class="anchored" data-anchor-id="survival-analysis">Survival Analysis</h2>
<section id="constructing-the-time-to-event-data" class="level3">
<h3 class="anchored" data-anchor-id="constructing-the-time-to-event-data">Constructing the Time-to-Event Data</h3>
<p>For closed complaints, the event time is the elapsed time between opening and closure. For complaints still open, the duration is measured from opening until the censoring cutoff.</p>
<p>The notebook used <strong>July 17, 2026 at 11:31 AM</strong>, the latest observed closure timestamp in the data, as its cutoff.</p>
<div id="survival-data" class="cell" data-execution_count="10">
<details class="code-fold">
<summary>Show code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb3"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>survival_df <span class="op">=</span> complaints.copy()</span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a>cutoff <span class="op">=</span> pd.Timestamp(<span class="st">"2026-07-17 11:31:00"</span>)</span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a>survival_df[<span class="st">"event_observed"</span>] <span class="op">=</span> (</span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a>    survival_df[<span class="st">"Date/Time Closed"</span>].notna().astype(<span class="bu">int</span>)</span>
<span id="cb3-7"><a href="#cb3-7" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb3-8"><a href="#cb3-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-9"><a href="#cb3-9" aria-hidden="true" tabindex="-1"></a>survival_df[<span class="st">"end_time"</span>] <span class="op">=</span> (</span>
<span id="cb3-10"><a href="#cb3-10" aria-hidden="true" tabindex="-1"></a>    survival_df[<span class="st">"Date/Time Closed"</span>].fillna(cutoff)</span>
<span id="cb3-11"><a href="#cb3-11" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb3-12"><a href="#cb3-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-13"><a href="#cb3-13" aria-hidden="true" tabindex="-1"></a>survival_df[<span class="st">"days_open"</span>] <span class="op">=</span> (</span>
<span id="cb3-14"><a href="#cb3-14" aria-hidden="true" tabindex="-1"></a>    survival_df[<span class="st">"end_time"</span>] <span class="op">-</span> survival_df[<span class="st">"Date/Time Opened"</span>]</span>
<span id="cb3-15"><a href="#cb3-15" aria-hidden="true" tabindex="-1"></a>).dt.total_seconds() <span class="op">/</span> <span class="dv">86400</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
<p>Here, <code>event_observed = 1</code> means the complaint closed during the observation period; <code>event_observed = 0</code> means it was still open at the cutoff.</p>
</section>
<section id="kaplanmeier-estimate" class="level3">
<h3 class="anchored" data-anchor-id="kaplanmeier-estimate">Kaplan–Meier Estimate</h3>
<p>I first estimated the overall survival curve nonparametrically using Kaplan–Meier estimation. In this setting, the survival function represents the probability that a complaint remains open beyond a given number of days.</p>
<div id="overall-km" class="cell" data-execution_count="11">
<div class="cell-output cell-output-display">
<div id="overall-km-1" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="wage-complaint-resolution_files/figure-html/overall-km-output-1.png" width="589" height="429" class="figure-img"></p>
<figcaption>Kaplan–Meier estimate of the probability that a complaint remains open.</figcaption>
</figure>
</div>
</div>
<div id="overall-km-2" class="cell-output cell-output-display" data-execution_count="11">
<pre><code>np.float64(39.84513888888889)</code></pre>
</div>
</div>
<p>The estimated median time to closure was approximately <strong>39.85 days</strong>. In other words, the Kaplan–Meier estimate falls to 0.5 at roughly 40 days.</p>
</section>
</section>
<section id="parametric-accelerate-failure-time-models" class="level2">
<h2 class="anchored" data-anchor-id="parametric-accelerate-failure-time-models">Parametric Accelerate Failure-Time Models</h2>
<p>To model how complaint characteristics relate to time-to-closure while accommodating censoring, I compared three parametric <strong>accelerated failure-time (AFT)</strong> specifications:</p>
<ol type="1">
<li>Weibull</li>
<li>Log-normal</li>
<li>Log-logistic</li>
</ol>
<p>The full specification used 24 intake and complaint-description features.</p>
<section id="holdout-performance" class="level3">
<h3 class="anchored" data-anchor-id="holdout-performance">Holdout Performance</h3>
<p>I evaluated discrimination using the concordance index (C-index). A higher C-index means the model is better at correctly ranking which of two complaints remains open longer.</p>
<div id="cell-aft-holdout-results" class="cell" data-execution_count="14">
<div id="aft-holdout-results" class="cell-output cell-output-display" data-execution_count="14">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">Model</th>
<th data-quarto-table-cell-role="th">Test C-index</th>
<th data-quarto-table-cell-role="th">Test log-likelihood</th>
<th data-quarto-table-cell-role="th">Training AIC</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<th data-quarto-table-cell-role="th">0</th>
<td>Weibull</td>
<td>0.577079</td>
<td>-3.320082</td>
<td>2146.594667</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">1</th>
<td>Log-normal</td>
<td>0.621124</td>
<td>-3.481862</td>
<td>2215.202074</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">2</th>
<td>Log-logistic</td>
<td>0.606292</td>
<td>-3.386675</td>
<td>2170.838844</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<p>In the notebook, the log-normal model had the highest single holdout C-index (<strong>0.621</strong>), followed by log-logistic (<strong>0.606</strong>) and Weibull (<strong>0.577</strong>).</p>
<p>A single train-test split can be noisy, however, so I also compared the models across five folds.</p>
</section>
<section id="five-fold-cross-validation" class="level3">
<h3 class="anchored" data-anchor-id="five-fold-cross-validation">Five-Fold Cross-Validation</h3>
<div id="cell-aft-cross-validation" class="cell" data-execution_count="15">
<div id="aft-cross-validation" class="cell-output cell-output-display" data-execution_count="15">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">Model</th>
<th data-quarto-table-cell-role="th">Mean CV C-index</th>
<th data-quarto-table-cell-role="th">SD</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<th data-quarto-table-cell-role="th">0</th>
<td>Weibull</td>
<td>0.542084</td>
<td>0.040162</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">1</th>
<td>Log-normal</td>
<td>0.523215</td>
<td>0.031702</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">2</th>
<td>Log-logistic</td>
<td>0.540076</td>
<td>0.044157</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<p>The notebook produced the following mean C-indices:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Model</th>
<th style="text-align: right;">Mean 5-fold C-index</th>
<th style="text-align: right;">SD</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Weibull</td>
<td style="text-align: right;">0.542</td>
<td style="text-align: right;">0.040</td>
</tr>
<tr class="even">
<td>Log-normal</td>
<td style="text-align: right;">0.523</td>
<td style="text-align: right;">0.032</td>
</tr>
<tr class="odd">
<td>Log-logistic</td>
<td style="text-align: right;">0.540</td>
<td style="text-align: right;">0.044</td>
</tr>
</tbody>
</table>
<p>This changes the interpretation of the single holdout result. Although the log-normal model performed best on that particular test set, its advantage did not persist across folds. <strong>Overall discrimination was modest, and the ranking of the three parametric models was not especially stable.</strong></p>
<p>That is a more useful conclusion than choosing a “winner” from one split.</p>
</section>
</section>
<section id="exploring-differences-in-resolution-curves" class="level2">
<h2 class="anchored" data-anchor-id="exploring-differences-in-resolution-curves">Exploring Differences in Resolution Curves</h2>
<p>I also used Kaplan–Meier curves and log-rank tests to explore whether particular binary complaint characteristics were associated with visibly different time-to-closure distributions.</p>
<p>Six variables produced log-rank p-values below 0.05 in the exploratory screen:</p>
<div id="cell-exploratory-km-results" class="cell" data-execution_count="17">
<div id="exploratory-km-results" class="cell-output cell-output-display" data-execution_count="17">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">Variable</th>
<th data-quarto-table-cell-role="th">Value</th>
<th data-quarto-table-cell-role="th">N</th>
<th data-quarto-table-cell-role="th">Observed closures</th>
<th data-quarto-table-cell-role="th">KM median days</th>
<th data-quarto-table-cell-role="th">Log-rank p-value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<th data-quarto-table-cell-role="th">0</th>
<td>deductions_or_benefits</td>
<td>0</td>
<td>354</td>
<td>235</td>
<td>39.846528</td>
<td>0.018576</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">1</th>
<td>deductions_or_benefits</td>
<td>1</td>
<td>20</td>
<td>17</td>
<td>33.043056</td>
<td>0.018576</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">2</th>
<td>leave_or_vacation_pay</td>
<td>0</td>
<td>336</td>
<td>235</td>
<td>38.282639</td>
<td>0.007875</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">3</th>
<td>leave_or_vacation_pay</td>
<td>1</td>
<td>38</td>
<td>17</td>
<td>103.097222</td>
<td>0.007875</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">4</th>
<td>overtime</td>
<td>0</td>
<td>342</td>
<td>235</td>
<td>38.647917</td>
<td>0.022375</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">5</th>
<td>overtime</td>
<td>1</td>
<td>32</td>
<td>17</td>
<td>178.027083</td>
<td>0.022375</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">6</th>
<td>ambiguous_primary</td>
<td>0</td>
<td>270</td>
<td>167</td>
<td>43.996528</td>
<td>0.001447</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">7</th>
<td>ambiguous_primary</td>
<td>1</td>
<td>104</td>
<td>85</td>
<td>36.793750</td>
<td>0.001447</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">8</th>
<td>multiple_workers</td>
<td>0</td>
<td>300</td>
<td>212</td>
<td>38.647917</td>
<td>0.049876</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">9</th>
<td>multiple_workers</td>
<td>1</td>
<td>74</td>
<td>40</td>
<td>47.116667</td>
<td>0.049876</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">10</th>
<td>description_quality_4.0</td>
<td>0</td>
<td>259</td>
<td>189</td>
<td>36.466667</td>
<td>0.000091</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">11</th>
<td>description_quality_4.0</td>
<td>1</td>
<td>115</td>
<td>63</td>
<td>74.100694</td>
<td>0.000091</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<p>The original notebook produced several large differences in estimated median time-to-closure. For example:</p>
<ul>
<li>Complaints with an <strong>overtime</strong> indicator had an estimated median of about <strong>178.0 days</strong>, compared with <strong>38.6 days</strong> for complaints without that indicator (<code>p ≈ 0.022</code>).</li>
<li>Complaints with a <strong>leave or vacation pay</strong> indicator had an estimated median of about <strong>103.1 days</strong>, compared with <strong>38.3 days</strong> for complaints without it (<code>p ≈ 0.0079</code>).</li>
<li>Complaints in the highest encoded <strong>description-quality category</strong> had an estimated median of about <strong>74.1 days</strong>, compared with <strong>36.5 days</strong> for other complaints (<code>p &lt; 0.001</code>).</li>
<li>Complaints involving <strong>multiple workers</strong> had an estimated median of about <strong>47.1 days</strong>, compared with <strong>38.6 days</strong> otherwise (<code>p ≈ 0.050</code>).</li>
</ul>
<p>These comparisons are <strong>exploratory associations, not causal effects</strong>. They were obtained by screening multiple variables separately, and some categories may contain relatively few complaints. The p-values should therefore be interpreted cautiously rather than as definitive evidence that a particular complaint characteristic causes longer or shorter resolution.</p>
<section id="example-kaplanmeier-comparison" class="level3">
<h3 class="anchored" data-anchor-id="example-kaplanmeier-comparison">Example Kaplan–Meier Comparison</h3>
<div id="cell-km-overtime" class="cell" data-execution_count="18">
<div class="cell-output cell-output-display">
<div id="km-overtime" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="wage-complaint-resolution_files/figure-html/km-overtime-output-1.png" width="663" height="429" class="figure-img"></p>
<figcaption>Estimated time-to-closure distributions for complaints with and without an overtime indicator.</figcaption>
</figure>
</div>
</div>
</div>
</section>
</section>
<section id="an-exploratory-reduced-model" class="level2">
<h2 class="anchored" data-anchor-id="an-exploratory-reduced-model">An Exploratory Reduced Model</h2>
<p>After the univariate Kaplan–Meier screen, I also fit AFT models using the six variables whose log-rank tests had p-values at or below 0.05.</p>
<p>Those reduced models produced mean five-fold C-indices of approximately:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Model</th>
<th style="text-align: right;">Mean 5-fold C-index</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Weibull</td>
<td style="text-align: right;">0.578</td>
</tr>
<tr class="even">
<td>Log-normal</td>
<td style="text-align: right;">0.572</td>
</tr>
<tr class="odd">
<td>Log-logistic</td>
<td style="text-align: right;">0.575</td>
</tr>
</tbody>
</table>
<p>These numbers are encouraging relative to the full 24-feature specification, but I would <strong>not treat them as final validation performance</strong>. The variables were selected after looking at the full dataset, so the selection step itself had access to information that later appeared in the evaluation folds.</p>
<p>A cleaner follow-up would perform feature screening <strong>inside each training fold</strong> or use a fully prespecified reduced feature set before evaluating on untouched data.</p>
</section>
<section id="what-i-learned" class="level2">
<h2 class="anchored" data-anchor-id="what-i-learned">What I Learned</h2>
<p>This project changed direction because the first model failed.</p>
<p>The initial linear-regression models had negative cross-validated R² across every specification I tried. Rather than treating that as a reason to keep tuning the same model, I reconsidered the structure of the outcome itself.</p>
<p>That led to three main conclusions:</p>
<ol type="1">
<li><p><strong>The available complaint metadata have limited predictive power for exact resolution time.</strong> Neither the large linear model nor simpler transformed variants generalized reliably.</p></li>
<li><p><strong>Survival analysis is a better formulation of the problem.</strong> It preserves information from complaints that remain unresolved rather than dropping nearly one-third of the dataset.</p></li>
<li><p><strong>Some complaint characteristics are associated with different resolution-time distributions, but prediction remains difficult.</strong> AFT models achieved only modest C-index performance, and exploratory Kaplan–Meier comparisons should not be interpreted causally.</p></li>
</ol>
<p>For an operational setting, that means these intake features may be more useful for <strong>risk stratification and identifying potentially long-running cases</strong> than for promising a precise number of days until closure.</p>
</section>
<section id="limitations-and-next-steps" class="level2">
<h2 class="anchored" data-anchor-id="limitations-and-next-steps">Limitations and Next Steps</h2>
<p>There are several reasons to keep the results modest.</p>
<ul>
<li><strong>Small sample:</strong> The dataset contains 374 complaints, only 252 of which had observed closures.</li>
<li><strong>Limited predictors:</strong> Intake metadata may omit important drivers of processing time, such as staffing, investigator workload, employer responsiveness, legal complexity, or changes in administrative procedure.</li>
<li><strong>Administrative censoring:</strong> The notebook used the latest observed closure time as the censoring cutoff. If the true data-extraction timestamp is available, that would be a more defensible administrative cutoff.</li>
<li><strong>Parametric assumptions:</strong> Weibull, log-normal, and log-logistic AFT models each impose assumptions about the distribution of survival times.</li>
<li><strong>Exploratory multiple testing:</strong> The Kaplan–Meier variable screen tested many predictors independently, so individual p-values should not be overinterpreted.</li>
<li><strong>Feature-selection leakage in the reduced model:</strong> The reduced feature set was identified using the full dataset before cross-validation. A future version should nest selection within training folds.</li>
<li><strong>No causal interpretation:</strong> The analysis is observational. Differences in survival curves do not establish that any complaint characteristic causes a delay.</li>
</ul>
<p>A next iteration could compare regularized survival models, survival forests, or boosting methods; use nested cross-validation for feature selection; and incorporate operational variables that better capture the administrative process itself.</p>
</section>
<section id="bottom-line" class="level2">
<h2 class="anchored" data-anchor-id="bottom-line">Bottom Line</h2>
<p>The strongest result was not a high accuracy score. It was recognizing that the original regression formulation was throwing away exactly the cases that make resolution-time modeling difficult.</p>
<p><strong>Moving from ordinary regression to censored time-to-event modeling allowed all 374 complaints to contribute information and produced a more defensible representation of the real operational problem.</strong></p>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("https:\/\/ronke4\.github\.io\/");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>